### PR TITLE
Fix for loading relative includes

### PR DESCRIPTION
**Pull request by tjittedevries**
Adding baseDir did the trick for me.

### CODE REVIEW

**Comment by tjittedevries** [comment]
Did you find some time to test this PR?

**Comment by tjittedevries** [comment]
@iketari Could you please check this PR? It would be nice if I could use this via NPM instead of my forked version 👍

**Review by iketari — APPROVED** [review]
All good!

**Comment by tjittedevries** [comment]
Thanks! I'll keep an eye on the npm page for the update :)

**Comment by iketari** [comment]
@tjittedevries + awesome-pug-jest@1.1.0

**Pull request merged**
